authentik:
    error_reporting:
        enabled: false
    disable_update_check: true
    disable_startup_analytics: true
    secret_key: "PleaseGenerateASecureKey"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: "ThisIsNotASecurePassword"
    # In the Helm values, set the akadmin user password and token:
    bootstrap_token: test
    bootstrap_password: test


server:
    ingress:
        enabled: false

postgresql:
    enabled: true
    auth:
        password: "ThisIsNotASecurePassword"
redis:
    enabled: true
