apiVersion: apps/v1
kind: Deployment
metadata:
  name: setup-oidc-provider
  namespace: authentik
  labels:
    app: setup-oidc-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: setup-oidc-provider
  template:
    metadata:
      labels:
        app: setup-oidc-provider
    spec:
      containers:
      - name: setup-oidc
        image: oidc-setup:latest
        env:
        - name: AUTHENTIK_TOKEN
          value: BZ6KJNzkCWzXORW2KsjTZXN8zC1VnHJYuLSaKLYf3zQzU5raikkhwiDHkI90 # Make some random scanner scream :D
        - name: AUTHENTIK_BASE_URL
          value: "http://authentik-server.authentik.svc.cluster.local:80"
        command: ["/bin/sh"]
        tty: true
        #command: ["python", "/app/setup-oidc-pkce-provider.py"]
        imagePullPolicy: IfNotPresent
