apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: service-a
  namespace: app
spec:
  spiffeIDTemplate: spiffe://example.org/ns/app/sa/service-a
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: ["service-a"]
      - key: serviceaccount
        operator: In
        values: ["service-a"]
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: ["app"]

---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: service-b
  namespace: app
spec:
  spiffeIDTemplate: spiffe://example.org/ns/app/sa/service-b
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: ["service-b"]
      - key: serviceaccount
        operator: In
        values: ["service-b"]
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: ["app"]