apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: dev
  namespace: spicedb
spec:
  config:
    datastoreEngine: memory
  secretName: dev-spicedb-config
  version: "v1.44.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-spicedb-config
  namespace: spicedb
stringData:
  preshared_key: "averysecretpresharedkey" 
