definition user {
  relation delegate: service
}

definition service {}

definition group {
  relation viewer: user
  relation editor: user
}

definition document {
  relation viewer_group: group
  relation editor_group: group
  relation deleter_group: group

  relation viewer_user: user
  relation editor_user: user
  relation deleter_user: user

  relation viewer_service: service
  relation editor_service: service
  relation deleter_service: service

  permission view = viewer_user + viewer_service
  permission edit = editor_user + editor_service
  permission delete = deleter_user + deleter_service
}

definition proxy_access {
  relation user: user
  relation service: service
  relation document: document

  relation user_is_viewer_group: group
  relation user_is_editor_group: group
  relation user_is_deleter_group: group

  permission delegated_view = document->viewer_user + document->viewer_service + user_is_viewer_group->viewer + user_is_viewer_group->editor + user_is_editor_group->editor
  permission delegated_edit = document->editor_user + document->editor_service + user_is_editor_group->editor
  permission delegated_delete = document->deleter_user + document->deleter_service + user_is_deleter_group->editor
}
