apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  namespace: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      serviceAccountName: service-b
      containers:
        - name: service-b
          image: service-b:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: app
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
